"use client";
/* eslint-disable @next/next/no-html-link-for-pages */
import { FormEvent, useState } from "react";
import { ArrowLeft, ArrowRight, Building2, Check, CheckCircle2, ChevronLeft, Clock3, MessageCircle, Send, ShieldCheck, Sparkles } from "lucide-react";
import "./form.css";

const types=["Retail & e-commerce","Restaurant & hospitality","Education & training","Logistics & delivery","Real estate & construction","Finance & professional services","Technology & IT services","NGO or public institution","Other"];
const services=["Business monitoring system","Inventory management","Employee and staff management","Productivity tracking","Website design and development","Mobile application","Telecom, USSD, SMS or IVR","API and payment integration","AI and workflow automation","Custom business software","Maintenance and technical support"];
type Data={businessName:string;ownerName:string;phone:string;email:string;location:string;businessType:string;services:string[];needs:string;software:string;employees:string;challenge:string;timeline:string;budget:string;details:string;contactMethod:string;notes:string;consent:boolean};
const empty:Data={businessName:"",ownerName:"",phone:"",email:"",location:"",businessType:"",services:[],needs:"",software:"",employees:"",challenge:"",timeline:"",budget:"",details:"",contactMethod:"",notes:"",consent:false};
const labels=["Business","Needs","Planning","Contact"];

export default function ProjectForm(){
 const [step,setStep]=useState(1),[data,setData]=useState(empty),[error,setError]=useState(""),[sending,setSending]=useState(false),[done,setDone]=useState(false);
 const set=<K extends keyof Data>(key:K,value:Data[K])=>setData(v=>({...v,[key]:value}));
 const toggle=(name:string)=>set("services",data.services.includes(name)?data.services.filter(x=>x!==name):[...data.services,name]);
 const issue=()=>step===1&&(!data.businessName||!data.ownerName||!data.phone||!data.email||!data.location||!data.businessType)?"Complete all business information.":step===2&&(!data.services.length||data.needs.trim().length<10||!data.employees)?"Select a service and describe what you need.":step===3&&(!data.challenge.trim()||!data.timeline)?"Add your main challenge and preferred timeline.":step===4&&(!data.contactMethod||!data.consent)?"Choose a contact method and accept the consent.":"";
 const next=()=>{const x=issue();if(x)return setError(x);setError("");setStep(v=>v+1);scrollTo({top:0,behavior:"smooth"})};
 const submit=async(e:FormEvent)=>{e.preventDefault();const x=issue();if(x)return setError(x);setSending(true);const message=[`Business: ${data.businessName}`,`Owner/manager: ${data.ownerName}`,`Location: ${data.location}`,`Business type: ${data.businessType}`,`Employees: ${data.employees}`,`Services: ${data.services.join(", ")}`,`Needs: ${data.needs}`,`Current software: ${data.software||"None stated"}`,`Main challenge: ${data.challenge}`,`Timeline: ${data.timeline}`,`Budget: ${data.budget||"Not stated"}`,`Project details: ${data.details||"None stated"}`,`Preferred contact: ${data.contactMethod}`,`Notes: ${data.notes||"None"}`].join("\n\n");try{const r=await fetch("/api/inquiries",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({kind:"project_onboarding",name:data.ownerName,contact:`${data.email} · ${data.phone}`,service:data.services.join(", "),message})});if(!r.ok)throw new Error();setDone(true)}catch{setError("Submission failed. Please try again or contact us on WhatsApp.")}finally{setSending(false)}};
 if(done)return <main className="intake"><section className="success"><CheckCircle2/><p>Project request received</p><h1>Thank you, {data.ownerName.split(" ")[0]}.</h1><span>Your request is now in the OceanBrown project desk. We’ll respond within 48 hours with the next steps.</span><div><a href="/">Return to website</a><a href="https://wa.me/2203631776" target="_blank" rel="noopener noreferrer"><MessageCircle/> WhatsApp us</a></div></section></main>;
 return <main className="intake"><header><a className="form-brand" href="/"><b>OB</b><strong>OceanBrown</strong></a><div><ShieldCheck/> Secure project request</div><a href="/"><ArrowLeft/> Back</a></header><div className="form-layout"><aside><p>Start a project</p><h1>Tell us what your business needs.</h1><span>Share enough context for us to recommend the right solution, delivery plan, and next steps.</span><small>Usually answered within 48 hours</small></aside><section className="form-work"><div className="progress"><div><span>Step {step} of 4</span><strong>{["Business information","Services and needs","Project planning","Communication"][step-1]}</strong></div><i><b style={{width:`${step*25}%`}}/></i><nav>{labels.map((x,i)=><button type="button" key={x} className={i+1===step?"active":i+1<step?"done":""} onClick={()=>i+1<step&&setStep(i+1)}><em>{i+1<step?<Check/>:i+1}</em>{x}</button>)}</nav></div><form onSubmit={submit}>
 {step===1&&<Panel icon={<Building2/>} title="Business information" copy="Help us understand who we will be working with."><div className="field-grid"><Field label="Business name" value={data.businessName} set={v=>set("businessName",v)} placeholder="e.g. Sunrise Retail Ltd"/><Field label="Owner or manager" value={data.ownerName} set={v=>set("ownerName",v)} placeholder="Your full name"/><Field label="Phone or WhatsApp" value={data.phone} set={v=>set("phone",v)} placeholder="+220 300 0000" type="tel"/><Field label="Email address" value={data.email} set={v=>set("email",v)} placeholder="you@business.com" type="email"/><Field label="Business location" value={data.location} set={v=>set("location",v)} placeholder="City, country"/><label>Type of business<select value={data.businessType} onChange={e=>set("businessType",e.target.value)}><option value="">Select business type</option>{types.map(x=><option key={x}>{x}</option>)}</select></label></div></Panel>}
 {step===2&&<Panel icon={<Sparkles/>} title="Services and needs" copy="Select everything that applies. We will refine the scope together."><fieldset className="choices"><legend>Services you are interested in</legend><div>{services.map(x=><label className={data.services.includes(x)?"selected":""} key={x}><input type="checkbox" checked={data.services.includes(x)} onChange={()=>toggle(x)}/><b><Check/></b>{x}</label>)}</div></fieldset><Area label="What would you like to improve?" value={data.needs} set={v=>set("needs",v)} placeholder="Describe the process, customer experience, or result you want to improve."/><div className="field-grid"><label>Number of employees<select value={data.employees} onChange={e=>set("employees",e.target.value)}><option value="">Select team size</option>{["Just me","2–5","6–20","21–50","More than 50"].map(x=><option key={x}>{x}</option>)}</select></label><Field label="Current software (optional)" value={data.software} set={v=>set("software",v)} placeholder="Tools you currently use"/></div></Panel>}
 {step===3&&<Panel icon={<Clock3/>} title="Project planning" copy="We use this information to recommend a realistic approach."><Area label="Biggest business challenge right now" value={data.challenge} set={v=>set("challenge",v)} placeholder="What is the main problem holding the business back?"/><div className="field-grid"><label>Preferred start timeline<select value={data.timeline} onChange={e=>set("timeline",e.target.value)}><option value="">Select timeline</option>{["As soon as possible","Within one month","Within 1–3 months","Within 3–6 months","Just exploring for now"].map(x=><option key={x}>{x}</option>)}</select></label><label>Estimated budget (optional)<select value={data.budget} onChange={e=>set("budget",e.target.value)}><option value="">Select budget</option>{["Under $500","$500–$1,500","$1,500–$5,000","$5,000–$15,000","Above $15,000","Need guidance"].map(x=><option key={x}>{x}</option>)}</select></label></div><Area label="Additional project details (optional)" value={data.details} set={v=>set("details",v)} placeholder="Mention features, users, integrations, deadlines, or other context."/></Panel>}
 {step===4&&<Panel icon={<Send/>} title="Communication" copy="Choose how you would like OceanBrown to follow up."><fieldset className="contact-method"><legend>Preferred communication method</legend><div>{["WhatsApp","Email","Phone call","Video call"].map(x=><label className={data.contactMethod===x?"selected":""} key={x}><input type="radio" checked={data.contactMethod===x} onChange={()=>set("contactMethod",x)}/>{x}</label>)}</div></fieldset><Area label="Additional notes (optional)" value={data.notes} set={v=>set("notes",v)} placeholder="Anything else we should know?"/><label className="consent"><input type="checkbox" checked={data.consent} onChange={e=>set("consent",e.target.checked)}/><b><Check/></b><span>I agree that OceanBrown may contact me regarding this request and use the information to prepare a tailored solution proposal.</span></label></Panel>}
 {error&&<p className="form-error" role="alert">{error}</p>}<footer>{step>1?<button type="button" onClick={()=>{setError("");setStep(v=>v-1)}}><ChevronLeft/> Previous</button>:<span/>}{step<4?<button type="button" className="continue" onClick={next}>Continue <ArrowRight/></button>:<button className="continue" disabled={sending}>{sending?"Submitting…":"Submit project request"}<Send/></button>}</footer></form></section></div></main>
}
function Panel({icon,title,copy,children}:{icon:React.ReactNode;title:string;copy:string;children:React.ReactNode}){return <div className="form-panel"><div className="panel-title">{icon}<div><h2>{title}</h2><p>{copy}</p></div></div>{children}</div>}
function Field({label,value,set,placeholder,type="text"}:{label:string;value:string;set:(v:string)=>void;placeholder:string;type?:string}){return <label>{label}<input required type={type} value={value} onChange={e=>set(e.target.value)} placeholder={placeholder}/></label>}
function Area({label,value,set,placeholder}:{label:string;value:string;set:(v:string)=>void;placeholder:string}){return <label className="wide">{label}<textarea rows={5} value={value} onChange={e=>set(e.target.value)} placeholder={placeholder}/></label>}
