"use client";
import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { Activity, BookOpen, Briefcase, ChevronRight, FileText, Globe2, HelpCircle, Image, Inbox, LayoutDashboard, Menu, MessageSquareQuote, Moon, Navigation, Package, Plus, RefreshCw, Search, Settings, ShieldCheck, Sparkles, Sun, Trash2, Users, X } from "lucide-react";

type Item={id:number;module:string;title:string;slug:string;summary:string;body:string;status:string;sortOrder:number;publishAt?:string;seoTitle:string;seoDescription:string;updatedAt:string};
type Inquiry={id:number;name:string;contact:string;service:string;message:string;status:string;createdAt:string};
const modules=[
 ["dashboard","Dashboard",LayoutDashboard],["pages","Pages",FileText],["services","Services",Sparkles],["products","Products",Package],["projects","Projects & case studies",Briefcase],["industries","Industries",Globe2],["team","Team",Users],["testimonials","Testimonials",MessageSquareQuote],["faqs","FAQs",HelpCircle],["blog","Blog & categories",BookOpen],["careers","Careers & applications",Briefcase],["inquiries","Contact inquiries",Inbox],["quotes","Quote requests",FileText],["subscribers","Newsletter subscribers",Users],["media","Media library",Image],["navigation","Navigation & footer",Navigation],["settings","Website settings",Settings],["users","Users & permissions",ShieldCheck],["activity","Activity log",Activity],
] as const;
const editable=new Set(["pages","services","products","projects","industries","team","testimonials","faqs","blog","careers","navigation"]);
const blank=(module:string):Partial<Item>=>({module,title:"",slug:"",summary:"",body:"",status:"draft",sortOrder:0,seoTitle:"",seoDescription:""});

export default function AdminApp({user}:{user:{name:string,email:string}}){
 const [section,setSection]=useState("dashboard"),[menu,setMenu]=useState(false),[dark,setDark]=useState(true),[items,setItems]=useState<Item[]>([]),[inquiries,setInquiries]=useState<Inquiry[]>([]),[loading,setLoading]=useState(true),[query,setQuery]=useState(""),[editing,setEditing]=useState<Partial<Item>|null>(null),[notice,setNotice]=useState("");
 useEffect(()=>{document.documentElement.dataset.adminTheme=dark?"dark":"light"},[dark]);
 const load=useCallback(async()=>{setLoading(true);try{const [a,b]=await Promise.all([fetch("/api/content"),fetch("/api/inquiries")]);if(a.ok)setItems(await a.json());if(b.ok)setInquiries(await b.json())}finally{setLoading(false)}},[]);
 useEffect(()=>{const frame=requestAnimationFrame(()=>{void load()});return()=>cancelAnimationFrame(frame)},[load]);
 const filtered=useMemo(()=>items.filter(x=>x.module===section&&(x.title+x.summary).toLowerCase().includes(query.toLowerCase())),[items,section,query]);
 const counts=useMemo(()=>({published:items.filter(x=>x.status==="published").length,draft:items.filter(x=>x.status==="draft").length,newInquiries:inquiries.filter(x=>x.status==="new").length,total:items.length}),[items,inquiries]);
 const navigate=(s:string)=>{setSection(s);setEditing(null);setMenu(false);setQuery("")};
 const save=async(e:FormEvent)=>{e.preventDefault();if(!editing)return;const method=editing.id?"PUT":"POST";const r=await fetch("/api/content",{method,headers:{"Content-Type":"application/json"},body:JSON.stringify(editing)});if(r.ok){setNotice(editing.id?"Changes saved and website content refreshed.":"Content created successfully.");setEditing(null);await load();setTimeout(()=>setNotice(""),3500)}else setNotice("Could not save this item. Check the slug and try again.")};
 const remove=async(id:number)=>{if(!confirm("Delete this item permanently?"))return;await fetch(`/api/content?id=${id}`,{method:"DELETE"});await load()};
 const updateInquiry=async(id:number,status:string)=>{await fetch("/api/inquiries",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({id,status})});await load()};
 const label=modules.find(x=>x[0]===section)?.[1]||"Dashboard";
 return <div className="admin-root">
  <aside className={menu?"admin-side open":"admin-side"}><div className="admin-brand"><span>OB</span><div>OceanBrown<small>Command Centre</small></div><button onClick={()=>setMenu(false)}><X/></button></div><nav>{modules.map(([id,name,Icon])=><button key={id} className={section===id?"active":""} onClick={()=>navigate(id)}><Icon/><span>{name}</span>{id==="inquiries"&&counts.newInquiries>0?<b>{counts.newInquiries}</b>:<ChevronRight className="chev"/>}</button>)}</nav><div className="admin-profile"><span>{user.name.slice(0,1).toUpperCase()}</span><div><strong>{user.name}</strong><small>System Owner</small></div></div></aside>
  {menu&&<button className="admin-scrim" aria-label="Close navigation" onClick={()=>setMenu(false)}/>}<main className="admin-main"><header><button className="admin-menu" onClick={()=>setMenu(true)}><Menu/></button><div><small>OceanBrown / {label}</small><h1>{label}</h1></div><div className="admin-actions"><button onClick={load} title="Refresh"><RefreshCw className={loading?"spin":""}/></button><button onClick={()=>setDark(!dark)} title="Change theme">{dark?<Sun/>:<Moon/>}</button><a href="/" target="_blank"><Globe2/><span>View website</span></a></div></header>{notice&&<div className="admin-notice">{notice}</div>}
  {section==="dashboard"&&<Dashboard counts={counts} inquiries={inquiries} items={items} onGo={navigate}/>} 
  {editable.has(section)&&<section className="admin-content"><div className="content-tools"><div className="admin-search"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={`Search ${label.toLowerCase()}...`}/></div><button className="admin-primary" onClick={()=>setEditing(blank(section))}><Plus/> Add new</button></div>{loading?<Loading/>:<ContentTable rows={filtered} onEdit={setEditing} onDelete={remove}/>}</section>}
  {section==="inquiries"&&<InquiryTable rows={inquiries} update={updateInquiry}/>} 
  {["quotes","subscribers","media","settings","users","activity"].includes(section)&&<ModulePanel section={section}/>} 
  {editing&&<Editor item={editing} setItem={setEditing} onClose={()=>setEditing(null)} onSave={save}/>}</main>
 </div>
}
function Dashboard({counts,inquiries,items,onGo}:{counts:{published:number;draft:number;newInquiries:number;total:number};inquiries:Inquiry[];items:Item[];onGo:(s:string)=>void}){return <><section className="welcome"><div><span>Operations overview</span><h2>Your website, content and client activity in one place.</h2><p>Publish confidently, follow new enquiries, and keep OceanBrown’s public presence current.</p></div><ShieldCheck/></section><section className="stat-grid"><article><span className="blue"><Globe2/></span><div><small>Published content</small><strong>{counts.published}</strong><em>Live on the website</em></div></article><article><span className="orange"><FileText/></span><div><small>Drafts</small><strong>{counts.draft}</strong><em>Waiting for review</em></div></article><article><span className="green"><Inbox/></span><div><small>New inquiries</small><strong>{counts.newInquiries}</strong><em>Require a response</em></div></article><article><span className="purple"><Activity/></span><div><small>Total records</small><strong>{counts.total}</strong><em>Across all modules</em></div></article></section><section className="dashboard-grid"><article className="panel"><div className="panel-head"><div><small>Client pipeline</small><h3>Latest inquiries</h3></div><button onClick={()=>onGo("inquiries")}>View all</button></div>{inquiries.slice(0,5).map(x=><div className="activity-row" key={x.id}><span>{x.name.slice(0,1)}</span><div><strong>{x.name}</strong><small>{x.service||"General enquiry"}</small></div><time>{new Date(x.createdAt).toLocaleDateString()}</time></div>)}{!inquiries.length&&<Empty text="New website inquiries will appear here."/>}</article><article className="panel"><div className="panel-head"><div><small>Content desk</small><h3>Recently updated</h3></div><button onClick={()=>onGo("pages")}>Manage</button></div>{items.slice(0,5).map(x=><div className="activity-row" key={x.id}><span><FileText/></span><div><strong>{x.title}</strong><small>{x.module} · {x.status.replace("_"," ")}</small></div><time>{new Date(x.updatedAt).toLocaleDateString()}</time></div>)}{!items.length&&<Empty text="Create your first managed content record."/>}</article></section></>}
function ContentTable({rows,onEdit,onDelete}:{rows:Item[];onEdit:(x:Item)=>void;onDelete:(id:number)=>void}){return <div className="admin-table"><div className="table-head"><span>Content</span><span>Status</span><span>Updated</span><span>Actions</span></div>{rows.map(x=><div className="table-row" key={x.id}><div><strong>{x.title}</strong><small>/{x.slug}</small></div><span className={`status-pill ${x.status}`}>{x.status.replace("_"," ")}</span><time>{new Date(x.updatedAt).toLocaleDateString()}</time><div className="row-actions"><button onClick={()=>onEdit(x)}>Edit</button><button className="danger" onClick={()=>onDelete(x.id)} aria-label={`Delete ${x.title}`}><Trash2/></button></div></div>)}{!rows.length&&<Empty text="No content here yet. Add the first item."/>}</div>}
function InquiryTable({rows,update}:{rows:Inquiry[];update:(id:number,s:string)=>void}){return <section className="admin-content"><div className="inquiry-list">{rows.map(x=><article key={x.id}><div className="inquiry-top"><div><span className={`status-pill ${x.status}`}>{x.status}</span><h3>{x.name}</h3><a href={`mailto:${x.contact}`}>{x.contact}</a></div><time>{new Date(x.createdAt).toLocaleString()}</time></div><strong>{x.service||"General enquiry"}</strong><p>{x.message}</p><div><button onClick={()=>update(x.id,"in_progress")}>Mark in progress</button><button onClick={()=>update(x.id,"resolved")}>Resolve</button></div></article>)}{!rows.length&&<Empty text="Contact form submissions will arrive here."/>}</div></section>}
function Editor({item,setItem,onClose,onSave}:{item:Partial<Item>;setItem:(x:Partial<Item>)=>void;onClose:()=>void;onSave:(e:FormEvent)=>void}){const set=(k:keyof Item,v:string|number)=>setItem({...item,[k]:v});return <div className="editor-backdrop"><form className="editor" onSubmit={onSave}><div className="editor-head"><div><small>{item.id?"Edit content":"New content"}</small><h2>{item.title||"Untitled item"}</h2></div><button type="button" onClick={onClose}><X/></button></div><div className="editor-grid"><label>Title<input required value={item.title||""} onChange={e=>{set("title",e.target.value);if(!item.id)set("slug",e.target.value.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,""))}}/></label><label>URL slug<input required value={item.slug||""} onChange={e=>set("slug",e.target.value)}/></label><label className="wide">Summary<textarea rows={3} value={item.summary||""} onChange={e=>set("summary",e.target.value)}/></label><label className="wide">Content / details<textarea rows={8} value={item.body||""} onChange={e=>set("body",e.target.value)} placeholder="Add the full content or structured details here."/></label><label>Status<select value={item.status||"draft"} onChange={e=>set("status",e.target.value)}><option value="draft">Draft</option><option value="published">Published</option><option value="scheduled">Scheduled</option><option value="coming_soon">Coming soon</option></select></label><label>Display order<input type="number" value={item.sortOrder||0} onChange={e=>set("sortOrder",Number(e.target.value))}/></label><label className="wide">SEO title<input value={item.seoTitle||""} onChange={e=>set("seoTitle",e.target.value)}/></label><label className="wide">SEO description<textarea rows={2} value={item.seoDescription||""} onChange={e=>set("seoDescription",e.target.value)}/></label></div><div className="editor-footer"><button type="button" onClick={onClose}>Cancel</button><button className="admin-primary" type="submit">Save changes</button></div></form></div>}
function ModulePanel({section}:{section:string}){const copy:Record<string,[string,string]>= {quotes:["Quote request workflow","Qualified quote requests will appear separately from general enquiries."],subscribers:["Newsletter audience","Subscriber records and consent history will be managed here."],media:["Media library","Upload and organise website images, documents and brand assets."],settings:["Website settings","Manage contact details, social links, SEO defaults and maintenance mode."],users:["Users and permissions","System Owner controls for administrators, roles and access."],activity:["Security activity","Administrative publishing and account actions are recorded here."]};const [title,text]=copy[section];return <section className="admin-content"><div className="module-card"><span><Settings/></span><h2>{title}</h2><p>{text}</p><b>Module prepared · No placeholder records published</b></div></section>}
function Empty({text}:{text:string}){return <div className="empty-state"><FileText/><p>{text}</p></div>} function Loading(){return <div className="empty-state"><RefreshCw className="spin"/><p>Loading current records…</p></div>}
