import { NextRequest, NextResponse } from "next/server";
import { desc, eq } from "drizzle-orm";
import { getChatGPTUser } from "../../chatgpt-auth";
import { getDb } from "../../../db";
import { activityLog, contentItems } from "../../../db/schema";
async function admin() { return getChatGPTUser(); }
export async function GET(request: NextRequest) { if (!await admin()) return NextResponse.json({ error: "Unauthorised" }, { status: 401 }); const moduleFilter = request.nextUrl.searchParams.get("module"); const db = getDb(); const rows = moduleFilter ? await db.select().from(contentItems).where(eq(contentItems.module, moduleFilter)).orderBy(contentItems.sortOrder) : await db.select().from(contentItems).orderBy(desc(contentItems.updatedAt)); return NextResponse.json(rows); }
export async function POST(request: NextRequest) { const user = await admin(); if (!user) return NextResponse.json({ error: "Unauthorised" }, { status: 401 }); const data = await request.json() as Record<string, unknown>; const now = new Date().toISOString(); const title = String(data.title || "Untitled").trim(); const slug = String(data.slug || title.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,"")); const result = await getDb().insert(contentItems).values({module:String(data.module||"pages"),title,slug,summary:String(data.summary||""),body:String(data.body||""),status:(data.status as "draft"|"scheduled"|"published"|"coming_soon")||"draft",sortOrder:Number(data.sortOrder||0),publishAt:data.publishAt?String(data.publishAt):null,seoTitle:String(data.seoTitle||""),seoDescription:String(data.seoDescription||""),createdAt:now,updatedAt:now}).returning(); await getDb().insert(activityLog).values({actorEmail:user.email,action:"created",entityType:String(data.module||"content"),entityId:String(result[0].id),createdAt:now}); return NextResponse.json(result[0], { status: 201 }); }
export async function PUT(request: NextRequest) { const user = await admin(); if (!user) return NextResponse.json({ error: "Unauthorised" }, { status: 401 }); const data = await request.json() as Record<string, unknown>; const id = Number(data.id); if (!id) return NextResponse.json({ error: "Missing id" }, { status: 400 }); const now = new Date().toISOString(); const update = {title:String(data.title||"Untitled"),slug:String(data.slug||""),summary:String(data.summary||""),body:String(data.body||""),status:(data.status as "draft"|"scheduled"|"published"|"coming_soon")||"draft",sortOrder:Number(data.sortOrder||0),publishAt:data.publishAt?String(data.publishAt):null,seoTitle:String(data.seoTitle||""),seoDescription:String(data.seoDescription||""),updatedAt:now}; const result = await getDb().update(contentItems).set(update).where(eq(contentItems.id,id)).returning(); await getDb().insert(activityLog).values({actorEmail:user.email,action:"updated",entityType:String(data.module||"content"),entityId:String(id),createdAt:now}); return NextResponse.json(result[0]); }
export async function DELETE(request: NextRequest) { const user = await admin(); if (!user) return NextResponse.json({ error: "Unauthorised" }, { status: 401 }); const id = Number(request.nextUrl.searchParams.get("id")); if (!id) return NextResponse.json({ error: "Missing id" }, { status: 400 }); await getDb().delete(contentItems).where(eq(contentItems.id,id)); await getDb().insert(activityLog).values({actorEmail:user.email,action:"deleted",entityType:"content",entityId:String(id),createdAt:new Date().toISOString()}); return NextResponse.json({ ok: true }); }
