import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";
import { query } from "../../../db";
import { getAdminSession, isSameOrigin } from "../../../lib/auth";
export const runtime = "nodejs";
const fields=`id,module,title,slug,summary,body,status,sort_order AS "sortOrder",publish_at AS "publishAt",seo_title AS "seoTitle",seo_description AS "seoDescription",created_at AS "createdAt",updated_at AS "updatedAt"`;
const content=z.object({id:z.coerce.number().int().positive().optional(),module:z.string().max(50),title:z.string().trim().min(1).max(180),slug:z.string().trim().regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/).max(180),summary:z.string().max(1000).default(""),body:z.string().max(50000).default(""),status:z.enum(["draft","scheduled","published","coming_soon"]),sortOrder:z.coerce.number().int().min(0).max(10000).default(0),publishAt:z.string().nullable().optional(),seoTitle:z.string().max(180).default(""),seoDescription:z.string().max(500).default("")});
async function admin(){return getAdminSession()}
export async function GET(request:NextRequest){if(!await admin())return NextResponse.json({error:"Unauthorised"},{status:401});const moduleFilter=request.nextUrl.searchParams.get("module");const result=moduleFilter?await query(`SELECT ${fields} FROM content_items WHERE module=$1 ORDER BY sort_order`,[moduleFilter]):await query(`SELECT ${fields} FROM content_items ORDER BY updated_at DESC`);return NextResponse.json(result.rows)}
export async function POST(request:NextRequest){const user=await admin();if(!user)return NextResponse.json({error:"Unauthorised"},{status:401});if(!isSameOrigin(request))return NextResponse.json({error:"Invalid origin"},{status:403});const parsed=content.safeParse(await request.json().catch(()=>null));if(!parsed.success)return NextResponse.json({error:"Invalid content"},{status:400});const d=parsed.data;const result=await query(`INSERT INTO content_items (module,title,slug,summary,body,status,sort_order,publish_at,seo_title,seo_description) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING ${fields}`,[d.module,d.title,d.slug,d.summary,d.body,d.status,d.sortOrder,d.publishAt||null,d.seoTitle,d.seoDescription]);await query(`INSERT INTO activity_log(actor_email,action,entity_type,entity_id) VALUES($1,'created',$2,$3)`,[user.email,d.module,String(result.rows[0].id)]);return NextResponse.json(result.rows[0],{status:201})}
export async function PUT(request:NextRequest){const user=await admin();if(!user)return NextResponse.json({error:"Unauthorised"},{status:401});if(!isSameOrigin(request))return NextResponse.json({error:"Invalid origin"},{status:403});const parsed=content.required({id:true}).safeParse(await request.json().catch(()=>null));if(!parsed.success)return NextResponse.json({error:"Invalid content"},{status:400});const d=parsed.data;const result=await query(`UPDATE content_items SET module=$1,title=$2,slug=$3,summary=$4,body=$5,status=$6,sort_order=$7,publish_at=$8,seo_title=$9,seo_description=$10,updated_at=now() WHERE id=$11 RETURNING ${fields}`,[d.module,d.title,d.slug,d.summary,d.body,d.status,d.sortOrder,d.publishAt||null,d.seoTitle,d.seoDescription,d.id]);await query(`INSERT INTO activity_log(actor_email,action,entity_type,entity_id) VALUES($1,'updated',$2,$3)`,[user.email,d.module,String(d.id)]);return NextResponse.json(result.rows[0])}
export async function DELETE(request:NextRequest){const user=await admin();if(!user)return NextResponse.json({error:"Unauthorised"},{status:401});if(!isSameOrigin(request))return NextResponse.json({error:"Invalid origin"},{status:403});const id=Number(request.nextUrl.searchParams.get("id"));if(!Number.isInteger(id)||id<1)return NextResponse.json({error:"Invalid id"},{status:400});await query(`DELETE FROM content_items WHERE id=$1`,[id]);await query(`INSERT INTO activity_log(actor_email,action,entity_type,entity_id) VALUES($1,'deleted','content',$2)`,[user.email,String(id)]);return NextResponse.json({ok:true})}
