"use client";
/* eslint-disable @next/next/no-html-link-for-pages */
/* The hero uses an audited local WebP with fixed dimensions and responsive sizing. */
/* eslint-disable @next/next/no-img-element */

import { FormEvent, useEffect, useState } from "react";
import { ArrowRight, Bot, BriefcaseBusiness, Check, ChevronDown, Cloud, Code2, Globe2, LayoutDashboard, Menu, MessageCircle, Moon, Network, Play, ShieldCheck, Smartphone, Sparkles, Sun, X } from "lucide-react";

const heroSlides=[
  {kicker:"Software built around your business",title:"One technology partner. Every digital possibility.",copy:"From first idea to daily operation, OceanBrown designs and builds software that makes work simpler, faster, and more connected."},
  {kicker:"Web & mobile experiences",title:"Digital products people understand and enjoy using.",copy:"Responsive websites and mobile applications engineered for real users, everyday devices, and measurable business outcomes."},
  {kicker:"Telecom, AI & automation",title:"Connect the systems that keep your business moving.",copy:"USSD, SMS, APIs, WhatsApp automation, dashboards, reporting, and intelligent workflows—brought together securely."},
];
const services=[
  {icon:Code2,n:"01",title:"Custom software",text:"Business platforms, internal portals, management systems, and customer applications shaped around your workflow.",items:["Discovery and architecture","Secure full-stack development","Deployment and support"]},
  {icon:Globe2,n:"02",title:"Web development",text:"High-performing websites and e-commerce experiences designed to explain, persuade, and convert.",items:["Corporate and campaign sites","E-commerce platforms","SEO and analytics"]},
  {icon:Smartphone,n:"03",title:"Mobile applications",text:"Reliable Android and iOS products built for local realities and long-term growth.",items:["Cross-platform development","Offline-friendly experiences","Store launch support"]},
  {icon:Network,n:"04",title:"Telecom solutions",text:"Operational tools and integrations backed by hands-on experience across value-added services.",items:["USSD, SMS and IVR","API and payment integration","Monitoring and reporting"]},
  {icon:Bot,n:"05",title:"AI & automation",text:"Connected workflows and practical AI that reduce repetitive work without losing human oversight.",items:["WhatsApp Business automation","AI support agents","Workflow automation"]},
  {icon:Cloud,n:"06",title:"Cloud & technical support",text:"Secure deployment, maintenance, performance work, and support that continues after launch.",items:["Cloud infrastructure","Security and audits","Maintenance agreements"]},
];
const products=[
  {name:"GNM",status:"Available",type:"Mobile utility",copy:"Helping people safely update Gambian contacts during the national numbering migration.",accent:"#0b7cff",metrics:[["Platform","iOS + Android"],["Focus","Contact migration"],["Built for","The Gambia"]]},
  {name:"MansaMart",status:"In development",type:"Commerce ecosystem",copy:"One connected marketplace for customers, merchants, riders, and platform operators.",accent:"#f59a3c",metrics:[["Apps","4 connected"],["Model","Marketplace"],["Focus","Local commerce"]]},
  {name:"MansaPay",status:"Coming soon",type:"Payments platform",copy:"A considered digital-payment experience designed for simpler, more connected transactions.",accent:"#11a888",metrics:[["Stage","Product design"],["Type","Fintech"],["Goal","Easy payments"]]},
  {name:"OceanBrain",status:"Research",type:"Applied AI",copy:"Exploring useful AI tools for customer support, business operations, and knowledge access.",accent:"#7957e8",metrics:[["Area","Applied AI"],["Stage","Research"],["Focus","Business tools"]]},
];
const industries=["Telecommunications","Retail & commerce","Financial services","NGOs & development","Education","Public sector","Hospitality","Professional services"];
const faqs=[
  ["What kinds of projects does OceanBrown take on?","We build websites, mobile applications, custom business systems, telecom integrations, automation, AI-enabled workflows, and connected digital platforms."],
  ["Can you improve an existing product?","Yes. We can audit an existing website or application, repair problems, improve performance and security, modernise the experience, or continue development."],
  ["Do you support clients after launch?","Yes. Support can cover monitoring, updates, backups, security, performance, reporting, and planned feature improvements."],
  ["How does a project begin?","Tell us the problem, goal, or idea. We clarify the scope, recommend an approach, and provide the next steps before development starts."],
];
type ManagedInsight={id:number;module:string;title:string;summary:string;body:string;status:string;sortOrder:number};

function Brand(){return <a href="/#top" className="brand" aria-label="OceanBrown home"><img className="brand-logo" src="/oceanbrown-logo.png" alt="OceanBrown — Software Development and IT Services" width="629" height="129"/></a>}

export default function Home(){
 const [menu,setMenu]=useState(false),[dark,setDark]=useState(true),[slide,setSlide]=useState(0),[product,setProduct]=useState(0),[faq,setFaq]=useState<number|null>(0),[sent,setSent]=useState(""),[managedInsights,setManagedInsights]=useState<ManagedInsight[]>([]);
 useEffect(()=>{const t=setInterval(()=>setSlide(v=>(v+1)%heroSlides.length),6500);return()=>clearInterval(t)},[]);
 useEffect(()=>{if(window.location.hostname==="publicadmin.oceanbrown.gm")window.location.replace("/admin")},[]);
 useEffect(()=>{const saved=localStorage.getItem("oceanbrown-theme");const prefersDark=window.matchMedia("(prefers-color-scheme: dark)").matches;const frame=requestAnimationFrame(()=>setDark(saved?saved==="dark":prefersDark));return()=>cancelAnimationFrame(frame)},[]);
 useEffect(()=>{document.documentElement.dataset.theme=dark?"dark":"light"},[dark]);
 useEffect(()=>{const controller=new AbortController();fetch("/api/public-content",{signal:controller.signal}).then(r=>r.ok?r.json():[]).then((rows:ManagedInsight[])=>setManagedInsights(rows.filter(x=>x.module==="blog").slice(0,6))).catch(()=>{});return()=>controller.abort()},[]);
 const toggleTheme=()=>setDark(current=>{const next=!current;localStorage.setItem("oceanbrown-theme",next?"dark":"light");return next});
 const send=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const form=e.currentTarget;const d=new FormData(form);setSent("Sending…");const r=await fetch("/api/inquiries",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:d.get("name"),contact:d.get("contact"),service:d.get("service"),message:d.get("message")})});if(r.ok){setSent("Thank you. Your enquiry is now in our project desk and we’ll respond within 48 hours.");form.reset()}else setSent("We could not send your enquiry. Please use WhatsApp or email instead.")};
 const hs=heroSlides[slide],p=products[product];
 return <main id="top"><a className="skip-link" href="#services">Skip to main content</a>
  <header className="site-header"><div className="nav-shell"><Brand/><nav className={menu?"nav-links open":"nav-links"} aria-label="Main navigation"><a href="#services" onClick={()=>setMenu(false)}>Services</a><a href="#products" onClick={()=>setMenu(false)}>Products</a><a href="#industries" onClick={()=>setMenu(false)}>Industries</a><a href="#about" onClick={()=>setMenu(false)}>Company</a><a href="#insights" onClick={()=>setMenu(false)}>Insights</a><a className="button small" href="#contact" onClick={()=>setMenu(false)}>Start a project <ArrowRight size={15}/></a></nav><div className="nav-tools"><button className="theme-button" onClick={toggleTheme} aria-label={`Switch to ${dark?"light":"dark"} mode`} title={`Switch to ${dark?"light":"dark"} mode`}>{dark?<Sun size={18}/>:<Moon size={18}/>}</button><button className="menu-button" onClick={()=>setMenu(!menu)} aria-label="Toggle menu">{menu?<X/>:<Menu/>}</button></div></div></header>
  <section className="hero"><img src="/oceanbrown-network.webp" alt="Digital connections flowing across Africa" className="hero-image" width="1920" height="1210" fetchPriority="high"/><div className="hero-shade"/><div className="hero-orbit orbit-one"/><div className="hero-orbit orbit-two"/><div className="hero-content section-shell"><div className="hero-copy-wrap" key={slide}><p className="eyebrow"><span/>{hs.kicker}</p><h1>{hs.title}</h1><p className="hero-copy">{hs.copy}</p><div className="hero-actions"><a className="button" href="#contact">Build with us <ArrowRight size={18}/></a><a className="ghost-button" href="#products"><Play size={16} fill="currentColor"/> Explore our products</a></div></div><div className="hero-console" aria-label="Illustration of connected digital operations"><div className="console-bar"><span/><span/><span/><b>OCEANBROWN / SYSTEMS</b></div><div className="console-body"><div className="console-head"><Sparkles size={20}/><span>Digital operations</span><i>LIVE</i></div><div className="signal-chart" aria-hidden="true"><span/><span/><span/><span/><span/><span/><span/><span/></div><div className="console-grid"><div><small>Projects</small><strong>Connected</strong></div><div><small>Security</small><strong>Protected</strong></div><div><small>Support</small><strong>Active</strong></div><div><small>Growth</small><strong>Scalable</strong></div></div></div></div></div><div className="hero-bottom section-shell"><div className="slide-controls" aria-label="Hero messages">{heroSlides.map((_,i)=><button type="button" key={i} className={slide===i?"active":""} onClick={()=>setSlide(i)} aria-label={`Show hero message ${i+1}`} aria-current={slide===i?"true":undefined}><span/></button>)}</div><div className="hero-proof"><span>Software engineering</span><span>Product design</span><span>Telecom solutions</span><span>Digital transformation</span></div></div></section>
  <section className="trust-strip"><div className="section-shell"><p>Built for organisations that need technology to work</p><div><span>Businesses</span><span>Institutions</span><span>Entrepreneurs</span><span>NGOs</span><span>Public sector</span><span>International partners</span></div></div></section>
  <section className="intro section-shell"><div><p className="section-label">One connected partner</p><h2>From a business challenge to a working digital system.</h2></div><div className="intro-copy"><p>OceanBrown is a youth-led Gambian technology company. We combine product thinking, engineering, telecom experience, and dependable support so clients do not need ten disconnected providers.</p><a href="#about">Discover OceanBrown <ArrowRight size={17}/></a></div></section>
  <section id="services" className="services-section"><div className="section-shell"><div className="section-heading"><div><p className="section-label">Capabilities</p><h2>Everything needed to move from idea to impact.</h2></div><p>Choose one focused service or bring us the complete problem. We assemble the right technical path around the outcome you need.</p></div><div className="services-grid">{services.map(({icon:Icon,...s})=><article className="service-card" key={s.title}><div className="service-icon"><Icon size={25}/></div><span>{s.n}</span><h3>{s.title}</h3><p>{s.text}</p><ul>{s.items.map(x=><li key={x}><Check size={14}/>{x}</li>)}</ul><a href="#contact">Discuss this service <ArrowRight size={15}/></a></article>)}</div></div></section>
  <section id="products" className="products-section"><div className="section-shell"><div className="section-heading light"><div><p className="section-label">OceanBrown products</p><h2>Products shaped by real local needs.</h2></div><p>We build our own technology as well as client solutions. Every status shown here reflects the product’s current stage.</p></div><div className="product-tabs" role="tablist" aria-label="OceanBrown products">{products.map((x,i)=><button type="button" role="tab" aria-selected={product===i} aria-controls="product-panel" id={`product-tab-${i}`} onClick={()=>setProduct(i)} className={product===i?"active":""} key={x.name}><span style={{background:x.accent}}/>{x.name}<small>{x.status}</small></button>)}</div><div className="product-stage" id="product-panel" role="tabpanel" aria-labelledby={`product-tab-${product}`} key={p.name}><div className="product-story"><p className="status"><span style={{background:p.accent}}/>{p.status}</p><p className="product-type">{p.type}</p><h3>{p.name}</h3><p>{p.copy}</p><div className="product-actions"><a className="button" href="#contact">Ask about {p.name} <ArrowRight size={16}/></a></div></div><div className="product-ui" style={{"--product-accent":p.accent} as React.CSSProperties} aria-label={`${p.name} product interface preview`}><div className="ui-sidebar" aria-hidden="true"><div className="mini-brand">{p.name.slice(0,2)}</div><LayoutDashboard/><BriefcaseBusiness/><MessageCircle/><ShieldCheck/></div><div className="ui-main"><div className="ui-top"><div><small>Product workspace</small><strong>{p.name}</strong></div><span>OceanBrown</span></div><div className="metric-grid">{p.metrics.map(([a,b])=><div key={a}><small>{a}</small><strong>{b}</strong></div>)}</div><div className="ui-chart"><div className="chart-label"><span>Activity</span><small>Latest overview</small></div><div className="bars" aria-hidden="true">{[42,66,52,79,63,88,74,95].map((h,i)=><i key={i} style={{height:`${h}%`}}/>)}</div></div></div></div></div></div></section>
  <section id="industries" className="industries section-shell"><div className="industries-copy"><p className="section-label">Industries</p><h2>Technology grounded in how your sector actually operates.</h2><p>We learn the workflow, constraints, and people behind each organisation before choosing the solution.</p><a className="text-arrow" href="#contact">Talk about your industry <ArrowRight size={17}/></a></div><div className="industry-list">{industries.map((x,i)=><div key={x}><span>0{i+1}</span><strong>{x}</strong><ArrowRight size={18}/></div>)}</div></section>
  <section id="about" className="about-section"><div className="section-shell about-grid"><div className="about-visual"><span className="visual-ring one"/><span className="visual-ring two"/><div className="africa-word">AFRICA<small>Connected to opportunity</small></div><div className="about-chip chip-one">The Gambia · HQ</div><div className="about-chip chip-two">Built for scale</div></div><div className="about-copy"><p className="section-label">Why OceanBrown</p><h2>Local understanding. Global engineering standards.</h2><p>We know the conditions our clients work in—from connectivity and everyday devices to payment realities and operational pressure. That understanding helps us make better technical decisions.</p><div className="value-grid"><div><strong>Understand first</strong><span>We define the real problem before proposing technology.</span></div><div><strong>Build responsibly</strong><span>Security, accessibility, and maintainability are part of the work.</span></div><div><strong>Communicate clearly</strong><span>You know what is being built and what happens next.</span></div><div><strong>Stay involved</strong><span>Launch is a milestone, not the end of the relationship.</span></div></div></div></div></section>
  <section className="security section-shell"><div><ShieldCheck size={34}/><p className="section-label">Built with care</p><h2>Dependability is a feature.</h2></div><div className="security-grid"><article><strong>Secure by design</strong><p>Thoughtful access, data protection, validation, and deployment practices.</p></article><article><strong>Made for every screen</strong><p>Responsive, accessible experiences that remain clear on everyday devices.</p></article><article><strong>Ready to evolve</strong><p>Maintainable foundations that can grow as requirements and users change.</p></article></div></section>
  <section id="insights" className="insights section-shell"><div className="section-heading"><div><p className="section-label">Ideas & insights</p><h2>Useful thinking for digital growth.</h2></div><a className="text-arrow" href="#contact">Request a consultation <ArrowRight size={17}/></a></div><div className="insight-grid">{managedInsights.length?managedInsights.map(item=><article key={item.id}><span>OceanBrown insight</span><h3>{item.title}</h3><p>{item.summary||item.body}</p></article>):<><article><span>Guide</span><h3>How to choose the right software for a growing Gambian business</h3><p>Start with the workflow and the outcome—not the technology trend.</p></article><article><span>Perspective</span><h3>What reliable digital transformation actually looks like</h3><p>Connected tools, clear ownership, trained people, and continuous improvement.</p></article><article><span>Telecom</span><h3>Turning operational data into decisions teams can act on</h3><p>Better reporting makes incidents, quality, and customer experience visible.</p></article></>}</div></section>
  <section className="faq-section"><div className="section-shell faq-grid"><div><p className="section-label">Frequently asked</p><h2>Before we begin.</h2><p>Clear answers to the questions clients often ask before starting a project.</p></div><div className="faq-list">{faqs.map(([q,a],i)=><article className={faq===i?"open":""} key={q}><button type="button" onClick={()=>setFaq(faq===i?null:i)} aria-expanded={faq===i} aria-controls={`faq-answer-${i}`}><span>{q}</span><ChevronDown size={19}/></button><div id={`faq-answer-${i}`}><p>{a}</p></div></article>)}</div></div></section>
  <section id="contact" className="contact-section"><div className="section-shell contact-grid"><div><p className="eyebrow dark"><span/> Start something useful</p><h2>Bring us the problem. We’ll help shape the solution.</h2><p>Tell us what you are trying to achieve. We usually respond within 48 hours with clear next steps.</p><div className="contact-direct"><a href="https://wa.me/2203631776" target="_blank" rel="noopener noreferrer"><MessageCircle size={18}/> WhatsApp: +220 363 1776</a><a href="mailto:info.oceanbrown@gmail.com">info.oceanbrown@gmail.com</a></div></div><form className="contact-form" onSubmit={send}><label>Name<input required name="name" autoComplete="name" placeholder="Your full name"/></label><label>Email or phone<input required name="contact" autoComplete="email" placeholder="How should we reach you?"/></label><label className="full">What do you need?<select name="service" defaultValue="Custom software"><option>Custom software</option><option>Website or e-commerce</option><option>Mobile application</option><option>Telecom or integration</option><option>AI or automation</option><option>Support or consultation</option><option>Something else</option></select></label><label className="full">Project details<textarea required name="message" rows={4} placeholder="Describe the challenge, goal, or idea."/></label><button className="button full" type="submit">Send project enquiry <ArrowRight size={17}/></button><small className="full" aria-live="polite">{sent||"Your message goes securely to the OceanBrown project desk."}</small></form></div></section>
  <footer><div className="section-shell footer-top"><div><Brand/><p>Practical technology, thoughtfully built in The Gambia.</p></div><div><strong>Company</strong><a href="#about">About</a><a href="#products">Products</a><a href="#insights">Insights</a><a href="#contact">Contact</a></div><div><strong>Services</strong><a href="#services">Software</a><a href="#services">Web & mobile</a><a href="#services">Telecom</a><a href="#services">AI & automation</a></div><div><strong>Contact</strong><a href="mailto:info.oceanbrown@gmail.com">info.oceanbrown@gmail.com</a><a href="tel:+2203631776">+220 363 1776</a><a href="tel:+2207140022">+220 714 0022</a><span>Banjul, The Gambia</span></div></div><div className="section-shell footer-bottom"><span>© 2026 OceanBrown. All rights reserved.</span><div><a href="/privacy">Privacy</a><a href="/terms">Terms</a><button type="button" onClick={toggleTheme}>{dark?<Sun size={14}/>:<Moon size={14}/>} {dark?"Light":"Dark"} mode</button></div></div></footer>
  <a className="whatsapp" href="https://wa.me/2203631776" target="_blank" rel="noopener noreferrer" aria-label="Contact OceanBrown on WhatsApp"><MessageCircle/><span>WhatsApp us</span></a>
 </main>
}
